FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o exporter ./cmd/exporter

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/exporter .
RUN apk add curl whois bash && curl -sL nxtrace.org/nt | bash
EXPOSE 20831
CMD ["./exporter"]
