FROM golang:1.24-alpine AS builder
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -o exporter ./cmd/exporter

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/exporter .
EXPOSE 20831
CMD ["./exporter"]
