FROM caddy:2.11.2-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/darkweak/souin/plugins/caddy

FROM caddy:2.11.2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY Caddyfile /etc/caddy/Caddyfile
EXPOSE [3010,2019]